name: docker-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -

        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: peanut974
          password: cazou974Yano
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: peanut974/pat-app:latest
